/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as ImoveisCodeRouteImport } from './routes/imoveis.$code'
import { Route as AdminCrmRouteImport } from './routes/admin.crm'
import { Route as ApiPublicNearbyOverpassRouteImport } from './routes/api/public/nearby-overpass'
import { Route as ApiPublicPropertiesSyncRouteImport } from './routes/api/public/properties/sync'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisCodeRoute = ImoveisCodeRouteImport.update({
  id: '/imoveis/$code',
  path: '/imoveis/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNearbyOverpassRoute = ApiPublicNearbyOverpassRouteImport.update({
  id: '/api/public/nearby-overpass',
  path: '/api/public/nearby-overpass',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPropertiesSyncRoute = ApiPublicPropertiesSyncRouteImport.update({
  id: '/api/public/properties/sync',
  path: '/api/public/properties/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/crm': typeof AdminCrmRoute
  '/imoveis/$code': typeof ImoveisCodeRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/api/public/nearby-overpass': typeof ApiPublicNearbyOverpassRoute
  '/api/public/properties/sync': typeof ApiPublicPropertiesSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/crm': typeof AdminCrmRoute
  '/imoveis/$code': typeof ImoveisCodeRoute
  '/imoveis': typeof ImoveisIndexRoute
  '/api/public/nearby-overpass': typeof ApiPublicNearbyOverpassRoute
  '/api/public/properties/sync': typeof ApiPublicPropertiesSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/crm': typeof AdminCrmRoute
  '/imoveis/$code': typeof ImoveisCodeRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/api/public/nearby-overpass': typeof ApiPublicNearbyOverpassRoute
  '/api/public/properties/sync': typeof ApiPublicPropertiesSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/admin/crm'
    | '/imoveis/$code'
    | '/imoveis/'
    | '/api/public/nearby-overpass'
    | '/api/public/properties/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/admin/crm'
    | '/imoveis/$code'
    | '/imoveis'
    | '/api/public/nearby-overpass'
    | '/api/public/properties/sync'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/admin/crm'
    | '/imoveis/$code'
    | '/imoveis/'
    | '/api/public/nearby-overpass'
    | '/api/public/properties/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminCrmRoute: typeof AdminCrmRoute
  ImoveisCodeRoute: typeof ImoveisCodeRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
  ApiPublicNearbyOverpassRoute: typeof ApiPublicNearbyOverpassRoute
  ApiPublicPropertiesSyncRoute: typeof ApiPublicPropertiesSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$code': {
      id: '/imoveis/$code'
      path: '/imoveis/$code'
      fullPath: '/imoveis/$code'
      preLoaderRoute: typeof ImoveisCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nearby-overpass': {
      id: '/api/public/nearby-overpass'
      path: '/api/public/nearby-overpass'
      fullPath: '/api/public/nearby-overpass'
      preLoaderRoute: typeof ApiPublicNearbyOverpassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties/sync': {
      id: '/api/public/properties/sync'
      path: '/api/public/properties/sync'
      fullPath: '/api/public/properties/sync'
      preLoaderRoute: typeof ApiPublicPropertiesSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminCrmRoute: AdminCrmRoute,
  ImoveisCodeRoute: ImoveisCodeRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
  ApiPublicNearbyOverpassRoute: ApiPublicNearbyOverpassRoute,
  ApiPublicPropertiesSyncRoute: ApiPublicPropertiesSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
