/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as ImoveisSlugRouteImport } from './routes/imoveis.$slug'
import { Route as AdminCrmRouteImport } from './routes/admin.crm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisSlugRoute = ImoveisSlugRouteImport.update({
  id: '/imoveis/$slug',
  path: '/imoveis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/crm': typeof AdminCrmRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/imoveis/': typeof ImoveisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/crm': typeof AdminCrmRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/imoveis': typeof ImoveisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/crm': typeof AdminCrmRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/imoveis/': typeof ImoveisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/crm' | '/imoveis/$slug' | '/imoveis/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/crm' | '/imoveis/$slug' | '/imoveis'
  id: '__root__' | '/' | '/admin/crm' | '/imoveis/$slug' | '/imoveis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCrmRoute: typeof AdminCrmRoute
  ImoveisSlugRoute: typeof ImoveisSlugRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$slug': {
      id: '/imoveis/$slug'
      path: '/imoveis/$slug'
      fullPath: '/imoveis/$slug'
      preLoaderRoute: typeof ImoveisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCrmRoute: AdminCrmRoute,
  ImoveisSlugRoute: ImoveisSlugRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
